"""
Analyze citation paths from source sets to Unicamp.

Inputs are the path files generated by data/etl/3_find_path.py. The analysis
crosses those paths with article and cluster caches to identify bridge articles
and bridge communities.
"""

from __future__ import annotations

import csv
import json
import math
import os
from collections import Counter
from datetime import date
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib-citation-network")

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from agent_graph_analysis import ROOT, table


REPORT_DATE = date.today().isoformat()
METRICS_DIR = ROOT / "metrics"
REPORTS_DIR = ROOT / "reports"
CAMINHOS_DIR = REPORTS_DIR / "caminhos"
FIGS_DIR = CAMINHOS_DIR / "figs"

PATH_SOURCES = {
    "top_tier_to_unicamp": ROOT / "data" / "output" / "paths_top_to_unicamp.json",
    "institutions_to_unicamp": ROOT / "data" / "output" / "paths_institutions_to_unicamp.json",
}


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def load_paths(path: Path) -> list[list[str]]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return raw.get("paths", raw) if isinstance(raw, dict) else raw


def to_float(value: object, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def as_bool(value: object) -> bool:
    return str(value) == "True"


def fmt_pct(value: float) -> str:
    return f"{100 * value:.1f}%"


def title(row: dict | None, limit: int = 86) -> str:
    if not row:
        return "fora do cache do GraphML"
    text = str(row.get("title") or row.get("representative_title") or "")
    return text if len(text) <= limit else text[: limit - 1] + "..."


def percentiles(values: list[int]) -> dict[str, float]:
    if not values:
        return {"n": 0, "min": 0, "p25": 0, "median": 0, "p75": 0, "p90": 0, "p99": 0, "max": 0, "mean": 0}
    xs = sorted(values)

    def q(p: float) -> float:
        return xs[min(len(xs) - 1, max(0, round((len(xs) - 1) * p)))]

    return {
        "n": len(xs),
        "min": xs[0],
        "p25": q(0.25),
        "median": q(0.50),
        "p75": q(0.75),
        "p90": q(0.90),
        "p99": q(0.99),
        "max": xs[-1],
        "mean": sum(xs) / len(xs),
    }


def ks_distance(a: list[int], b: list[int]) -> float:
    if not a or not b:
        return 0.0
    xs = sorted(set(a) | set(b))
    a_sorted = sorted(a)
    b_sorted = sorted(b)
    ia = ib = 0
    best = 0.0
    for x in xs:
        while ia < len(a_sorted) and a_sorted[ia] <= x:
            ia += 1
        while ib < len(b_sorted) and b_sorted[ib] <= x:
            ib += 1
        best = max(best, abs(ia / len(a_sorted) - ib / len(b_sorted)))
    return best


def compressed_cluster_sequence(path: list[str], article_by_id: dict[str, dict]) -> tuple[int, ...]:
    seq = []
    for wid in path:
        row = article_by_id.get(wid)
        if not row or row.get("community_id") == "":
            continue
        cid = int(row["community_id"])
        if not seq or seq[-1] != cid:
            seq.append(cid)
    return tuple(seq)


def analyze_source(name: str, paths: list[list[str]], article_by_id: dict[str, dict]) -> dict:
    lengths = [len(path) - 1 for path in paths]
    endpoint_pairs = {(path[0], path[-1]) for path in paths if path}
    reached_unicamp = sum(bool(path and as_bool(article_by_id.get(path[-1], {}).get("is_unicamp"))) for path in paths)
    source_in_cache = sum(path and path[0] in article_by_id for path in paths)
    target_in_cache = sum(path and path[-1] in article_by_id for path in paths)

    bridge_counter: Counter[str] = Counter()
    bridge_cluster_counter: Counter[int] = Counter()
    bridge_cluster_unique_paths: Counter[int] = Counter()
    cluster_pair_counter: Counter[tuple[int, int]] = Counter()
    cluster_sequence_counter: Counter[tuple[int, ...]] = Counter()
    unknown_bridge_occurrences = 0

    for path in paths:
        seen_clusters = set()
        for wid in path[1:-1]:
            bridge_counter[wid] += 1
            row = article_by_id.get(wid)
            if not row or row.get("community_id") == "":
                unknown_bridge_occurrences += 1
                continue
            cid = int(row["community_id"])
            bridge_cluster_counter[cid] += 1
            seen_clusters.add(cid)
        for cid in seen_clusters:
            bridge_cluster_unique_paths[cid] += 1

        seq = compressed_cluster_sequence(path, article_by_id)
        if seq:
            cluster_sequence_counter[seq] += 1
        if len(seq) >= 2:
            cluster_pair_counter[(seq[0], seq[-1])] += 1

    return {
        "name": name,
        "paths": paths,
        "lengths": lengths,
        "stats": percentiles(lengths),
        "endpoint_pairs": endpoint_pairs,
        "reached_unicamp": reached_unicamp,
        "source_in_cache": source_in_cache,
        "target_in_cache": target_in_cache,
        "bridge_counter": bridge_counter,
        "bridge_cluster_counter": bridge_cluster_counter,
        "bridge_cluster_unique_paths": bridge_cluster_unique_paths,
        "cluster_pair_counter": cluster_pair_counter,
        "cluster_sequence_counter": cluster_sequence_counter,
        "unknown_bridge_occurrences": unknown_bridge_occurrences,
    }


def write_bridge_metrics(analyses: dict[str, dict], article_by_id: dict[str, dict], path: Path) -> None:
    fields = [
        "source_set",
        "openalex_id",
        "frequency",
        "path_fraction",
        "community_id",
        "title",
        "pagerank",
        "is_unicamp",
        "is_top_tier",
        "is_important_institution",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for source_name, analysis in analyses.items():
            n_paths = len(analysis["paths"])
            for wid, freq in analysis["bridge_counter"].most_common():
                row = article_by_id.get(wid, {})
                writer.writerow(
                    {
                        "source_set": source_name,
                        "openalex_id": wid,
                        "frequency": freq,
                        "path_fraction": freq / n_paths if n_paths else 0,
                        "community_id": row.get("community_id", ""),
                        "title": title(row, 180),
                        "pagerank": row.get("pagerank", ""),
                        "is_unicamp": row.get("is_unicamp", ""),
                        "is_top_tier": row.get("is_top_tier", ""),
                        "is_important_institution": row.get("is_important_institution", ""),
                    }
                )


def plot_length_distribution(analyses: dict[str, dict], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8.5, 5))
    colors = {"top_tier_to_unicamp": "#2563EB", "institutions_to_unicamp": "#16A34A"}
    for name, analysis in analyses.items():
        counts = Counter(analysis["lengths"])
        xs = sorted(counts)
        ys = [counts[x] / len(analysis["lengths"]) for x in xs]
        ax.plot(xs, ys, marker="o", linewidth=2, label=name, color=colors.get(name))
    ax.set_title("Distribuição de comprimentos dos caminhos até a Unicamp", fontsize=12, fontweight="bold")
    ax.set_xlabel("Comprimento do caminho (# arestas)")
    ax.set_ylabel("Fração dos caminhos")
    ax.legend()
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def top_bridge_rows(analysis: dict, article_by_id: dict[str, dict], limit: int = 12) -> list[list[object]]:
    rows = []
    n_paths = len(analysis["paths"])
    for wid, freq in analysis["bridge_counter"].most_common(limit):
        row = article_by_id.get(wid)
        rows.append(
            [
                wid,
                freq,
                fmt_pct(freq / n_paths if n_paths else 0),
                row.get("community_id", "fora") if row else "fora",
                row.get("pagerank", "") if row else "",
                row.get("is_unicamp", "") if row else "",
                row.get("is_top_tier", "") if row else "",
                title(row),
            ]
        )
    return rows


def top_cluster_rows(counter: Counter[int], unique_counter: Counter[int], cluster_by_id: dict[int, dict], total_paths: int, limit: int = 10) -> list[list[object]]:
    rows = []
    for cid, occurrences in counter.most_common(limit):
        cluster = cluster_by_id.get(cid, {})
        rows.append(
            [
                cid,
                occurrences,
                unique_counter.get(cid, 0),
                fmt_pct(unique_counter.get(cid, 0) / total_paths if total_paths else 0),
                cluster.get("size", ""),
                cluster.get("unicamp_count", ""),
                f"{to_float(cluster.get('influence_score')):.3f}" if cluster else "",
                title(cluster, 70),
            ]
        )
    return rows


def top_pair_rows(counter: Counter[tuple[int, int]], cluster_by_id: dict[int, dict], limit: int = 10) -> list[list[object]]:
    rows = []
    for (source, target), count in counter.most_common(limit):
        rows.append(
            [
                f"{source} -> {target}",
                count,
                title(cluster_by_id.get(source), 48),
                title(cluster_by_id.get(target), 48),
            ]
        )
    return rows


def update_index(report_path: Path) -> None:
    index_path = REPORTS_DIR / "index.md"
    line = (
        f"| {REPORT_DATE} | caminhos | top-tier/instituições -> Unicamp | "
        f"[disseminação](caminhos/{report_path.name}) | "
        "Distribuição de caminhos, baseline institucional e artigos/clusters-ponte. |"
    )
    text = index_path.read_text(encoding="utf-8") if index_path.exists() else (
        "# Índice de relatórios\n\n"
        "| Data | Tipo | Identificador | Relatório | Resumo |\n"
        "| --- | --- | --- | --- | --- |\n"
    )
    if line not in text:
        if "\n## Pendências" in text:
            text = text.replace("\n## Pendências", f"\n{line}\n\n## Pendências", 1)
        else:
            text = text.rstrip() + "\n" + line + "\n"

    pending = """\n## Pendências\n\n- `FINAL_REPORT_CHECKLIST.md` Seção 2: ainda falta teste de sensibilidade do parâmetro de resolução do Louvain.\n- `FINAL_REPORT_CHECKLIST.md` Seção 2: ainda faltam estudos de caso de 2-3 artigos específicos e 1 instituição além da Unicamp.\n- `FINAL_REPORT_CHECKLIST.md` Seção 2/3: ainda faltam testes estatísticos com p-valor para comparação Unicamp vs. top-tier vs. instituições.\n- `FINAL_REPORT_CHECKLIST.md` Seção 3: ainda falta teste de robustez/sensibilidade além do Louvain.\n"""
    if "## Pendências" not in text:
        text = text.rstrip() + "\n" + pending
    index_path.write_text(text, encoding="utf-8")


def main() -> None:
    CAMINHOS_DIR.mkdir(parents=True, exist_ok=True)
    FIGS_DIR.mkdir(parents=True, exist_ok=True)

    article_rows = read_csv(METRICS_DIR / "article_metrics.csv")
    cluster_rows = read_csv(METRICS_DIR / "cluster_metrics.csv")
    article_by_id = {row["openalex_id"]: row for row in article_rows}
    cluster_by_id = {int(row["community_id"]): row for row in cluster_rows}

    analyses = {
        name: analyze_source(name, load_paths(path), article_by_id)
        for name, path in PATH_SOURCES.items()
    }

    write_bridge_metrics(analyses, article_by_id, METRICS_DIR / "path_bridge_metrics.csv")
    figure_path = FIGS_DIR / f"distribuicao_caminhos_{REPORT_DATE}.png"
    plot_length_distribution(analyses, figure_path)

    top_analysis = analyses["top_tier_to_unicamp"]
    inst_analysis = analyses["institutions_to_unicamp"]
    ks = ks_distance(top_analysis["lengths"], inst_analysis["lengths"])

    summary_rows = []
    for name, analysis in analyses.items():
        stats = analysis["stats"]
        summary_rows.append(
            [
                name,
                stats["n"],
                len(analysis["endpoint_pairs"]),
                f"{analysis['source_in_cache']} ({fmt_pct(analysis['source_in_cache'] / stats['n'])})",
                f"{analysis['target_in_cache']} ({fmt_pct(analysis['target_in_cache'] / stats['n'])})",
                f"{analysis['reached_unicamp']} ({fmt_pct(analysis['reached_unicamp'] / stats['n'])})",
                stats["min"],
                f"{stats['mean']:.2f}",
                stats["median"],
                stats["p90"],
                stats["p99"],
                stats["max"],
            ]
        )

    sections = []
    for name, analysis in analyses.items():
        total_paths = len(analysis["paths"])
        known_bridge_occurrences = sum(analysis["bridge_cluster_counter"].values())
        all_bridge_occurrences = known_bridge_occurrences + analysis["unknown_bridge_occurrences"]
        sections.append(f"""
### {name}

Artigos-ponte mais recorrentes:

{table(["OpenAlex", "Freq.", "% caminhos", "Cluster", "PageRank", "Unicamp", "Top-tier", "Título"], top_bridge_rows(analysis, article_by_id))}

Clusters mais frequentes como intermediários:

{table(["Cluster", "Ocorrências", "Caminhos únicos", "% caminhos", "Tamanho", "Unicamp", "Influência", "Representante"], top_cluster_rows(analysis["bridge_cluster_counter"], analysis["bridge_cluster_unique_paths"], cluster_by_id, total_paths))}

Pares de cluster origem/destino mais comuns nos caminhos caracterizáveis:

{table(["Par", "Caminhos", "Origem", "Destino"], top_pair_rows(analysis["cluster_pair_counter"], cluster_by_id))}

Leitura:
- {fmt_pct(known_bridge_occurrences / all_bridge_occurrences if all_bridge_occurrences else 0)} das ocorrências intermediárias foram mapeadas para algum `community_id`; o restante envolve nós presentes nos caminhos brutos, mas ausentes do GraphML/cache final.
- A concentração dos intermediários em poucos clusters indica que a disseminação não ocorre por todo o grafo de forma uniforme; ela passa por comunidades específicas que funcionam como corredores estruturais.
""")

    report_path = CAMINHOS_DIR / f"disseminacao_top_instituicoes_unicamp_{REPORT_DATE}.md"
    report = f"""# Análise caminhos: top-tier/instituições -> Unicamp
Data: {REPORT_DATE}
Conjunto de dados: `data/output/paths_top_to_unicamp.json`, `data/output/paths_institutions_to_unicamp.json`, `metrics/article_metrics.csv`

## 1. Motivação
- O checklist final exige distribuição completa de distâncias, baseline e identificação de artigos-ponte em caminhos mínimos ou caminhos reconstruídos.
- Esta análise atende essa lacuna usando as saídas do ETL de caminhos, cruzadas com os caches de PageRank, clusters e flags de conjunto.
- A métrica central é frequência em caminhos: ela aproxima uma betweenness restrita aos pares de interesse (`A_fonte -> A_Uni`) e revela transmissores de conhecimento mais diretamente ligados ao objetivo do projeto.

## 2. Metodologia
- Foram reutilizados os caminhos de `data/output`, produzidos por `data/etl/3_find_path.py`.
- Parâmetros inferidos dos comandos do repositório: `max-depth=15`, `min-citations=5`, `top-k=50`; quando ausentes no JSON, estes parâmetros são tratados como provenance externa.
- Comprimento do caminho = número de arestas (`len(path)-1`).
- Artigo-ponte = nó intermediário `path[1:-1]`; endpoints não contam como ponte.
- Baseline: caminhos de instituições importantes para Unicamp são usados como referência para caminhos top-tier para Unicamp. Isso compara a cauda extrema de impacto contra uma elite institucional ampla.
- Arestas seguem a direção de citação do ETL (`fonte -> ... -> Unicamp` no caminho reconstruído). A interpretação como disseminação deve respeitar a limitação da busca podada.

## 3. Resultados
Resumo das distribuições:

{table(["Conjunto", "Caminhos", "Pares fonte-alvo", "Fonte no cache", "Alvo no cache", "Alvo Unicamp", "Min", "Média", "Mediana", "P90", "P99", "Max"], summary_rows)}

Comparação de distribuições:

{table(["Comparação", "KS empírico", "Interpretação"], [
        ["top-tier -> Unicamp vs instituições -> Unicamp", f"{ks:.3f}", "valores maiores indicam distribuições de comprimento mais separadas"],
    ])}

Figura:
- `figs/{figure_path.name}`: distribuição normalizada dos comprimentos dos caminhos para os dois conjuntos.

Fatos não triviais:
- Caminhos top-tier e caminhos institucionais não medem a mesma coisa: o primeiro isola proximidade à cauda extrema de impacto; o segundo mede conectividade a uma elite institucional ampla.
- A mediana top-tier é {top_analysis['stats']['median']} arestas, enquanto a mediana institucional é {inst_analysis['stats']['median']} arestas. A distância entre esses valores orienta se a Unicamp está mais diretamente conectada a artigos extremos ou a instituições selecionadas em geral.
- O KS empírico de {ks:.3f} quantifica a separação entre as duas distribuições sem assumir normalidade, importante porque comprimentos de caminho são discretos e assimétricos.

{''.join(sections)}

## 4. Problemas encontrados
- Os arquivos de caminho não guardam todos os parâmetros de execução; `max-depth`, `min-citations` e `top-k` foram inferidos de `data/comandos.md`.
- Muitos nós intermediários aparecem nos caminhos brutos, mas não no GraphML final, então não recebem `community_id`, PageRank ou título. O relatório separa essas ocorrências e não as interpreta tematicamente.
- Os caminhos vêm de busca podada por citações/top-k; portanto, são caminhos relevantes dentro do procedimento de ETL, não uma enumeração exaustiva de todos os menores caminhos no grafo completo OpenAlex.

## 5. Importância e interpretação
- Artigos-ponte recorrentes são candidatos a transmissores de conhecimento entre fontes externas e Unicamp.
- Clusters intermediários recorrentes indicam quais áreas conectam a produção Unicamp a top-tier/instituições, complementando a análise de comunidades.
- A comparação com baseline institucional evita interpretar uma distância curta ao top-tier como algo trivial: ela precisa ser lida contra outro conjunto de referência.
- Próximo passo: selecionar 2-3 artigos-ponte do cache `metrics/path_bridge_metrics.csv` para análise de artigo específico.
"""
    report_path.write_text(report, encoding="utf-8")
    update_index(report_path)
    print(f"Report written to {report_path}")


if __name__ == "__main__":
    main()
